query Recursive {
  book(id: "id_hoge") {
    title
    author {
      name
      books {
        title
        author {
          name
          books {
            title
          }
        }
      }
    }
  }
}
