mutation TestAdd {
  addBook(newBookData: { title: "titleeee" }) {
    id
    title
  }
}

query GetOneBookAndAuthor {
  book(id: "id_hoge") {
    ...bookFields
  }
  author(id: "first_id") {
    ...authorFields
  }
}

query CheckResult {
  allBooks {
    ...bookFields
  }
  allAuthors{
    ...authorFields
  }
}

fragment bookFields on Book {
  id
  title
  author {
    ...authorFields
  }
}
fragment authorFields on Author {
  id
  name
    books{
      title
    }
}
